-- CreateEnum
CREATE TYPE "AccountStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "AccountType" AS ENUM ('FNO', 'CASH', 'MF');

-- CreateEnum
CREATE TYPE "EntryType" AS ENUM ('FNO_INTRADAY', 'FNO_EQUITY', 'EQUITY', 'MCX', 'DIVIDEND', 'MF', 'FNO_EQUITY_ADJUSTMENT');

-- CreateEnum
CREATE TYPE "TrxType" AS ENUM ('BUY', 'SELL');

-- CreateEnum
CREATE TYPE "OwnedBy" AS ENUM ('IFIN', 'CUSTOMER');

-- CreateTable
CREATE TABLE "CRM" (
    "ifinId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "clientName" STRING NOT NULL,
    "brokerId" STRING NOT NULL,
    "phoneNo" CHAR(10) NOT NULL,
    "email" STRING NOT NULL,
    "address" STRING NOT NULL,
    "accountOpenDate" DATE NOT NULL,
    "accountType" "AccountType"[] DEFAULT ARRAY[]::"AccountType"[],
    "accountStatus" "AccountStatus" NOT NULL,

    CONSTRAINT "CRM_pkey" PRIMARY KEY ("ifinId")
);

-- CreateTable
CREATE TABLE "Credentials" (
    "credentialsId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647),
    "ifinId" INT4 NOT NULL,
    "applicationId" INT4 NOT NULL,
    "userName" STRING NOT NULL,
    "userPassword" STRING NOT NULL,
    "pin" STRING,

    CONSTRAINT "Credentials_pkey" PRIMARY KEY ("credentialsId")
);

-- CreateTable
CREATE TABLE "Application" (
    "applicationId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647),
    "name" STRING NOT NULL,

    CONSTRAINT "Application_pkey" PRIMARY KEY ("applicationId")
);

-- CreateTable
CREATE TABLE "Ledger" (
    "ledgerId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647),
    "ifinId" INT4 NOT NULL,
    "ledgerEntryTypeId" INT4 NOT NULL,
    "amount" DECIMAL(14,2) NOT NULL,
    "fromDate" DATE NOT NULL,
    "toDate" DATE NOT NULL,

    CONSTRAINT "Ledger_pkey" PRIMARY KEY ("ledgerId")
);

-- CreateTable
CREATE TABLE "LedgerEntryType" (
    "ledgerEntryTypeId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647),
    "comment" STRING NOT NULL,

    CONSTRAINT "LedgerEntryType_pkey" PRIMARY KEY ("ledgerEntryTypeId")
);

-- CreateTable
CREATE TABLE "ClientMargin" (
    "marginId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647),
    "ifinId" INT4 NOT NULL,
    "margin" DECIMAL(14,2) NOT NULL,

    CONSTRAINT "ClientMargin_pkey" PRIMARY KEY ("marginId")
);

-- CreateTable
CREATE TABLE "RealisedPnl" (
    "realisedPnlId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647),
    "ifinId" INT4 NOT NULL,
    "pnl" DECIMAL(14,2) NOT NULL,
    "entryType" "EntryType" NOT NULL,
    "fromDate" DATE NOT NULL,
    "toDate" DATE NOT NULL,

    CONSTRAINT "RealisedPnl_pkey" PRIMARY KEY ("realisedPnlId")
);

-- CreateTable
CREATE TABLE "PnlAdjustment" (
    "pnlAdjustmentId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647),
    "ifinId" INT4 NOT NULL,
    "adjustment" DECIMAL(14,2) NOT NULL,
    "comment" STRING NOT NULL,
    "fromDate" DATE NOT NULL,
    "toDate" DATE NOT NULL,

    CONSTRAINT "PnlAdjustment_pkey" PRIMARY KEY ("pnlAdjustmentId")
);

-- CreateTable
CREATE TABLE "HoldingsPnl" (
    "holdingsPnlId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647),
    "ifinId" INT4 NOT NULL,
    "holdingsNameId" INT4 NOT NULL,
    "trxType" "TrxType" NOT NULL,
    "trxPrice" DECIMAL(14,2) NOT NULL,
    "quantity" DECIMAL(14,2) NOT NULL,
    "trxDate" DATE NOT NULL,
    "ownedBy" "OwnedBy" NOT NULL,
    "fromDate" DATE NOT NULL,
    "toDate" DATE NOT NULL,

    CONSTRAINT "HoldingsPnl_pkey" PRIMARY KEY ("holdingsPnlId")
);

-- CreateTable
CREATE TABLE "HoldingsName" (
    "holdingsNameId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647),
    "name" STRING NOT NULL,
    "sector" STRING NOT NULL,
    "ticker" STRING NOT NULL,

    CONSTRAINT "HoldingsName_pkey" PRIMARY KEY ("holdingsNameId")
);

-- CreateTable
CREATE TABLE "Account" (
    "id" STRING NOT NULL,
    "userId" STRING NOT NULL,
    "type" STRING NOT NULL,
    "provider" STRING NOT NULL,
    "providerAccountId" STRING NOT NULL,
    "refresh_token" STRING,
    "access_token" STRING,
    "expires_at" INT4,
    "token_type" STRING,
    "scope" STRING,
    "id_token" STRING,
    "session_state" STRING,
    "refresh_token_expires_in" INT4,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" STRING NOT NULL,
    "sessionToken" STRING NOT NULL,
    "userId" STRING NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" STRING NOT NULL,
    "name" STRING,
    "email" STRING,
    "emailVerified" TIMESTAMP(3),
    "image" STRING,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VerificationToken" (
    "identifier" STRING NOT NULL,
    "token" STRING NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);

-- CreateIndex
CREATE INDEX "CRM_clientName_idx" ON "CRM"("clientName");

-- CreateIndex
CREATE UNIQUE INDEX "CRM_brokerId_phoneNo_email_key" ON "CRM"("brokerId", "phoneNo", "email");

-- CreateIndex
CREATE INDEX "HoldingsName_name_idx" ON "HoldingsName"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

-- AddForeignKey
ALTER TABLE "CRM" ADD CONSTRAINT "CRM_email_fkey" FOREIGN KEY ("email") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Credentials" ADD CONSTRAINT "Credentials_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("applicationId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Credentials" ADD CONSTRAINT "Credentials_ifinId_fkey" FOREIGN KEY ("ifinId") REFERENCES "CRM"("ifinId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Ledger" ADD CONSTRAINT "Ledger_ifinId_fkey" FOREIGN KEY ("ifinId") REFERENCES "CRM"("ifinId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Ledger" ADD CONSTRAINT "Ledger_ledgerEntryTypeId_fkey" FOREIGN KEY ("ledgerEntryTypeId") REFERENCES "LedgerEntryType"("ledgerEntryTypeId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClientMargin" ADD CONSTRAINT "ClientMargin_ifinId_fkey" FOREIGN KEY ("ifinId") REFERENCES "CRM"("ifinId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RealisedPnl" ADD CONSTRAINT "RealisedPnl_ifinId_fkey" FOREIGN KEY ("ifinId") REFERENCES "CRM"("ifinId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PnlAdjustment" ADD CONSTRAINT "PnlAdjustment_ifinId_fkey" FOREIGN KEY ("ifinId") REFERENCES "CRM"("ifinId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HoldingsPnl" ADD CONSTRAINT "HoldingsPnl_holdingsNameId_fkey" FOREIGN KEY ("holdingsNameId") REFERENCES "HoldingsName"("holdingsNameId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HoldingsPnl" ADD CONSTRAINT "HoldingsPnl_ifinId_fkey" FOREIGN KEY ("ifinId") REFERENCES "CRM"("ifinId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
